// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: urls.sql

package database

import (
	"context"
)

const createShortURL = `-- name: CreateShortURL :one
INSERT INTO urls (original_url, short_url_code) VALUES ($1, $2) RETURNING id, original_url, short_url_code, created_at, updated_at
`

type CreateShortURLParams struct {
	OriginalUrl  string
	ShortUrlCode string
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (Url, error) {
	row := q.db.QueryRowContext(ctx, createShortURL, arg.OriginalUrl, arg.ShortUrlCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrlCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShortURL = `-- name: GetShortURL :one
SELECT id, original_url, short_url_code, created_at, updated_at FROM urls WHERE short_url_code = $1
`

func (q *Queries) GetShortURL(ctx context.Context, shortUrlCode string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getShortURL, shortUrlCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortUrlCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
