// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
)

type Paste struct {
	ID        int64
	Content   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Title     string
	IsPublic  bool
	ExpiresAt sql.NullTime
}
