// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pastes.sql

package database

import (
	"context"
)

const createPaste = `-- name: CreatePaste :one
INSERT INTO pastes (content) VALUES ($1) RETURNING id, content, created_at, updated_at
`

func (q *Queries) CreatePaste(ctx context.Context, content string) (Paste, error) {
	row := q.db.QueryRowContext(ctx, createPaste, content)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPastes = `-- name: GetAllPastes :many
SELECT id, content, created_at, updated_at FROM pastes
`

func (q *Queries) GetAllPastes(ctx context.Context) ([]Paste, error) {
	rows, err := q.db.QueryContext(ctx, getAllPastes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Paste
	for rows.Next() {
		var i Paste
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaste = `-- name: GetPaste :one
SELECT id, content, created_at, updated_at FROM pastes WHERE id = $1
`

func (q *Queries) GetPaste(ctx context.Context, id int64) (Paste, error) {
	row := q.db.QueryRowContext(ctx, getPaste, id)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
