/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShortenUrlIndexRouteImport } from './routes/shorten-url/index'
import { Route as PastebinIndexRouteImport } from './routes/pastebin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortenUrlIndexRoute = ShortenUrlIndexRouteImport.update({
  id: '/shorten-url/',
  path: '/shorten-url/',
  getParentRoute: () => rootRouteImport,
} as any)
const PastebinIndexRoute = PastebinIndexRouteImport.update({
  id: '/pastebin/',
  path: '/pastebin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pastebin/': typeof PastebinIndexRoute
  '/shorten-url/': typeof ShortenUrlIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pastebin': typeof PastebinIndexRoute
  '/shorten-url': typeof ShortenUrlIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pastebin/': typeof PastebinIndexRoute
  '/shorten-url/': typeof ShortenUrlIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pastebin/' | '/shorten-url/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pastebin' | '/shorten-url'
  id: '__root__' | '/' | '/pastebin/' | '/shorten-url/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PastebinIndexRoute: typeof PastebinIndexRoute
  ShortenUrlIndexRoute: typeof ShortenUrlIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorten-url/': {
      id: '/shorten-url/'
      path: '/shorten-url'
      fullPath: '/shorten-url/'
      preLoaderRoute: typeof ShortenUrlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pastebin/': {
      id: '/pastebin/'
      path: '/pastebin'
      fullPath: '/pastebin/'
      preLoaderRoute: typeof PastebinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PastebinIndexRoute: PastebinIndexRoute,
  ShortenUrlIndexRoute: ShortenUrlIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
