// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
INSERT INTO oauth_identities (user_id, provider, provider_subject)
VALUES ($1, $2, $3)
`

type CreateOAuthIdentityParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Provider        string    `json:"provider"`
	ProviderSubject string    `json:"provider_subject"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthIdentity, arg.UserID, arg.Provider, arg.ProviderSubject)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO
    sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	TokenHash []byte    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name)
VALUES ($1, $2)
RETURNING id, email, display_name, created_at, updated_at
`

type CreateUserParams struct {
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE
    expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE
    id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT
    id,
    user_id,
    provider,
    provider_subject,
    created_at
FROM oauth_identities
WHERE
    provider = $1
    AND provider_subject = $2
`

type GetOAuthIdentityParams struct {
	Provider        string `json:"provider"`
	ProviderSubject string `json:"provider_subject"`
}

func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (OauthIdentity, error) {
	row := q.db.QueryRowContext(ctx, getOAuthIdentity, arg.Provider, arg.ProviderSubject)
	var i OauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, user_id, token_hash, expires_at, created_at
FROM sessions
WHERE
    token_hash = $1
    AND expires_at > now()
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, display_name, created_at, updated_at
FROM users
WHERE
    id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEmailAndDisplay = `-- name: UpdateUserEmailAndDisplay :exec
UPDATE users
SET
    email = $2,
    display_name = $3,
    updated_at = now()
WHERE
    id = $1
`

type UpdateUserEmailAndDisplayParams struct {
	ID          uuid.UUID      `json:"id"`
	Email       sql.NullString `json:"email"`
	DisplayName sql.NullString `json:"display_name"`
}

func (q *Queries) UpdateUserEmailAndDisplay(ctx context.Context, arg UpdateUserEmailAndDisplayParams) error {
	_, err := q.db.ExecContext(ctx, updateUserEmailAndDisplay, arg.ID, arg.Email, arg.DisplayName)
	return err
}
